name: Force Sync with Upstream Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:

jobs:
  force-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取所有历史

    - name: Force Sync master branch from upstream
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git remote add upstream https://github.com/ACL4SSR/ACL4SSR.git
        git fetch upstream
        git checkout --track upstream/master || git checkout -b master upstream/master
        git reset --hard upstream/master
        git push -f origin master
