name: Sync ACL4SSR Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync master branch of ACL4SSR

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Initialization environment
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Sync Repository
      env:
        ACCESS_TOKEN: ${{ secrets.MY_PAT }}  # 使用自定义的PAT
      run: |
        git clone -b master https://github.com/ACL4SSR/ACL4SSR.git synced_repo
        cd synced_repo
        if git status --porcelain | grep .; then
          git add .
          git commit -am "update $(date '+%Y-%m-%d %H:%M:%S')"
          git push --quiet "https://${{ secrets.MY_PAT }}@github.com/${{ github.repository }}" master
        else
          echo "nothing to commit"
          exit 0
        fi || exit 0

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.MY_PAT }}  # 同样使用自定义的PAT
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 1
