name: Manual Sync Fork

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * *'  # 还可以按计划定时运行

jobs:
  sync-master-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the master branch of the source repository
      uses: actions/checkout@v2
      with:
        repository: 'ACL4SSR/ACL4SSR'
        ref: 'master'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync the master branch
      uses: repo-sync/github-sync@v2
      with:
        source_repo: 'ACL4SSR/ACL4SSR'
        source_branch: 'master'
        destination_branch: 'master'
        github_token: ${{ secrets.GITHUB_TOKEN }}
