name: Sync with Upstream Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取所有历史

    - name: Sync master branch from upstream
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git remote add upstream https://github.com/ACL4SSR/ACL4SSR.git
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push https://${{ secrets.GIT_AUTH_TOKEN }}@github.com/ForeverXiang/ACL4SSR.git master
      env:
        GIT_AUTH_TOKEN: ${{ secrets.MY_PAT }}
